Sign In , SignUp and Splash screen Added
jay-a-shah/Repo-Simform-Team pull request #5
Opened 2022-03-28 06:25 UTC by jay-a-shah

2022-03-28 06:31 UTC, Purvesh-Dodiya requested changes

2022-03-28 06:31 UTC, Purvesh-Dodiya commented on app/src/main/java/com/example/simformcafeteria/SignUpActivity.kt
> +
empty lines

2022-03-28 06:31 UTC, Purvesh-Dodiya commented on app/src/main/res/layout/activity_main.xml
> +        android:textColor="#E64A19"
move color to color file

2022-03-28 06:31 UTC, Purvesh-Dodiya commented on app/src/main/res/layout/activity_main.xml
> +        android:textSize="30dp"
textSize should be in sp

2022-03-28 06:31 UTC, Purvesh-Dodiya commented on app/src/main/res/layout/activity_main.xml
> +        android:text="Sign in !"
static text

2022-03-28 06:31 UTC, Purvesh-Dodiya commented on app/src/main/res/layout/activity_main.xml
> +        app:boxStrokeColor="#434242"
move color to color file

2022-03-28 06:31 UTC, Purvesh-Dodiya commented on app/src/main/res/layout/activity_main.xml
> +        android:text="Sign In"
static string

2022-03-28 06:31 UTC, Purvesh-Dodiya commented on app/src/main/res/layout/activity_sign_up.xml
> +        android:text="Sign Up !"
static string

2022-03-28 06:31 UTC, Purvesh-Dodiya commented on app/src/main/res/layout/activity_sign_up.xml
> +        app:hintTextColor="#E64A19"
same for color

2022-03-28 06:31 UTC, Purvesh-Dodiya commented on app/src/main/res/layout/activity_sign_up.xml
> +
extra empty line

2022-03-28 06:31 UTC, Purvesh-Dodiya commented on app/src/main/res/layout/activity_sign_up.xml
> +        android:text="Trainee"
same for text, check in all the files

2022-03-29 04:39 UTC, Purvesh-Dodiya requested changes

2022-03-29 04:39 UTC, Purvesh-Dodiya commented on app/src/main/java/com/example/simformcafeteria/MainActivity.kt
> +import kotlinx.android.synthetic.main.activity_main.*
remove astric import

2022-03-29 04:39 UTC, Purvesh-Dodiya commented on app/src/main/java/com/example/simformcafeteria/SignUpActivity.kt
> +import kotlinx.android.synthetic.main.activity_sign_up.*
same

2022-03-30 06:47 UTC, purvesh-d requested changes
Also change the pattern of giving id in xml. Underscore or camel case chose any one

2022-03-30 06:47 UTC, purvesh-d commented on app/src/main/res/layout/activity_main.xml
> +
extra empty space

2022-03-30 06:47 UTC, purvesh-d commented on app/src/main/res/layout/activity_main.xml
> +        app:boxStrokeColor="#434242"
pending

2022-04-05 04:49 UTC, purvesh-d approved these changes

2022-04-05 04:49 UTC, purvesh-d commented on app/src/main/res/layout/activity_sign_up.xml
> +
pending

2022-04-05 05:01 UTC, purvesh-d approved these changes

2022-04-05 05:01 UTC, merged